### ISSUE TITLE
Analysis: Grid distance performance enhancement

### ISSUE THREAD

**Issue by TheDukeZip** [pdogg/jt65stego#24]
Instead of recalculating the grid distance for each packet, jt65analysis.py could build up a hash table of distances to grids, and look them up.

This may not be of much consequence to the actual performance, since the packet decoding probably takes up a large percentage of the time to run.

**Comment by pdogg** [comment]
Fixed in: https://github.com/pdogg/jt65stego/commit/4f965453e330fd91fcea1a67abcd8428dab2ebd8

There were multiple calcs of the same distance and I assume it is somewhat expensive do to multiple calls to mathy functions. Also removed the fact that home latlon was calculated in every call to output. This is a single call now.
